app_main:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET]

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: [GET, POST]

api_users:
    resource: routes/resources/api_users.yaml
    name_prefix: api_users_
    prefix: /api/users
